ALTER TABLE `world_guilds`
  ADD COLUMN IF NOT EXISTS `note` VARCHAR(256)
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `note_author` VARCHAR(50)
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `note_date` BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `informations` VARCHAR(2560)
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `informations_author` VARCHAR(50)
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `informations_date` BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `rank_names` VARCHAR(2048)
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
